webtalk_init -webtalk_dir D:/College/IIITD/Others/CA_Proj_Git_Bkp/RISC_Pipeline/RISC_Pipe_Git/RISC_Pipe_Git.sim/sim_1/behav/xsim/xsim.dir/IF_ID_EX_MA_RW_Test_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Nov  1 11:36:54 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "196199df-3d35-438f-8996-dcb19dfe136c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7d3a574d62ce487ca54e11fc174f3ac1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 4600H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2994 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "12" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "97 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "7 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "91" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "12" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.47_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "48316_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4267513995 -regid "" -xml D:/College/IIITD/Others/CA_Proj_Git_Bkp/RISC_Pipeline/RISC_Pipe_Git/RISC_Pipe_Git.sim/sim_1/behav/xsim/xsim.dir/IF_ID_EX_MA_RW_Test_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/College/IIITD/Others/CA_Proj_Git_Bkp/RISC_Pipeline/RISC_Pipe_Git/RISC_Pipe_Git.sim/sim_1/behav/xsim/xsim.dir/IF_ID_EX_MA_RW_Test_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/College/IIITD/Others/CA_Proj_Git_Bkp/RISC_Pipeline/RISC_Pipe_Git/RISC_Pipe_Git.sim/sim_1/behav/xsim/xsim.dir/IF_ID_EX_MA_RW_Test_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
